//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DriverResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DriverResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع السيارة.
        /// </summary>
        internal static string BrandID {
            get {
                return ResourceManager.GetString("BrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لون السيارة.
        /// </summary>
        internal static string ColorID {
            get {
                return ResourceManager.GetString("ColorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفاعل.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإضافة.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الرحله.
        /// </summary>
        internal static string CurrentTripID {
            get {
                return ResourceManager.GetString("CurrentTripID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الرخصه.
        /// </summary>
        internal static string DrivingLicenseNumber {
            get {
                return ResourceManager.GetString("DrivingLicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكترونى.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة السائق.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتبط برحلة.
        /// </summary>
        internal static string IsBusy {
            get {
                return ResourceManager.GetString("IsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IsExternal {
            get {
                return ResourceManager.GetString("IsExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المستخدم.
        /// </summary>
        internal static string IsOnline {
            get {
                return ResourceManager.GetString("IsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر خط عرض.
        /// </summary>
        internal static string LastLatitude {
            get {
                return ResourceManager.GetString("LastLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اخر دخول.
        /// </summary>
        internal static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر خط الطول.
        /// </summary>
        internal static string LastLongitude {
            get {
                return ResourceManager.GetString("LastLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LastUpdatedLocationDateTime {
            get {
                return ResourceManager.GetString("LastUpdatedLocationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم رخصة السيارة.
        /// </summary>
        internal static string LicenseNumber {
            get {
                return ResourceManager.GetString("LicenseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حمولة السيارة.
        /// </summary>
        internal static string MaxLoad {
            get {
                return ResourceManager.GetString("MaxLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديل السيارة.
        /// </summary>
        internal static string ModelID {
            get {
                return ResourceManager.GetString("ModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم السائق.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي.
        /// </summary>
        internal static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة الشخصية.
        /// </summary>
        internal static string PersonalImagePath {
            get {
                return ResourceManager.GetString("PersonalImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السيارة.
        /// </summary>
        internal static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقيم.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود السياره.
        /// </summary>
        internal static string VehicleID {
            get {
                return ResourceManager.GetString("VehicleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم السيارة.
        /// </summary>
        internal static string VehicleSizeID {
            get {
                return ResourceManager.GetString("VehicleSizeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنه السيارة.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
