//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LogTemplate", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ActionDetails.
        /// </summary>
        internal static string ActionDetails {
            get {
                return ResourceManager.GetString("ActionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ActionText.
        /// </summary>
        internal static string ActionText {
            get {
                return ResourceManager.GetString("ActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a target=&quot;_blank&quot; href=&quot;@AddEditPageLink &quot;&gt;@AddEditObjName&lt;/a&gt; .
        /// </summary>
        internal static string AddedEditedObjLnk {
            get {
                return ResourceManager.GetString("AddedEditedObjLnk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddEditObjName.
        /// </summary>
        internal static string AddEditObjName {
            get {
                return ResourceManager.GetString("AddEditObjName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @AddEditPageLink.
        /// </summary>
        internal static string AddEditPageLink {
            get {
                return ResourceManager.GetString("AddEditPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ClassIcon.
        /// </summary>
        internal static string ClassIcon {
            get {
                return ResourceManager.GetString("ClassIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف           .
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       تم القيام بعملية تعديل على.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @HourAction.
        /// </summary>
        internal static string HourAction {
            get {
                return ResourceManager.GetString("HourAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال .
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @IpAddress.
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @logDate.
        /// </summary>
        internal static string logDate {
            get {
                return ResourceManager.GetString("logDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;span&gt; @ActionText &lt;/span&gt;  &lt;span&gt;@ActionDetails &lt;/span&gt;.
        /// </summary>
        internal static string logDetails {
            get {
                return ResourceManager.GetString("logDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @LogID.
        /// </summary>
        internal static string logID {
            get {
                return ResourceManager.GetString("logID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول إلى النظام من عنوان الايبى  .
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج من النظام.
        /// </summary>
        internal static string LogOutText {
            get {
                return ResourceManager.GetString("LogOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li class=&quot;timeline-success&quot; id=&quot;@LogID&quot; &gt;
        ///							&lt;div class=&quot;timeline-icon&quot;&gt;&lt;i class=&quot;@ClassIcon&quot;&gt;&lt;/i&gt;&lt;/div&gt;
        ///							&lt;div class=&quot;timeline-body&quot;&gt;
        ///								&lt;div class=&quot;timeline-header&quot;&gt;
        ///									&lt;span class=&quot;author&quot;&gt;المستخدم &lt;a href=&quot;&quot;&gt;@UserName&lt;/a&gt;&lt;/span&gt;
        ///		&lt;span&gt;@logDate&lt;/span&gt;&lt;span class=&quot; loadlogtime&quot; hour=&quot;@HourAction&quot;
        ///                                    min=&quot;@MinAction&quot;&gt;&lt;/span&gt;							
        ///								&lt;/div&gt;
        ///								&lt;div class=&quot;timeline-content&quot;&gt;
        ///									&lt;h4&gt;العملية: @Action&lt;/h4&gt;
        ///									&lt;p&gt;@logDetail [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LogRecordItem {
            get {
                return ResourceManager.GetString("LogRecordItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @MinAction.
        /// </summary>
        internal static string MinAction {
            get {
                return ResourceManager.GetString("MinAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;empty&quot;&gt;
        ///        لا يوجد بيانات
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string NotFoundLog {
            get {
                return ResourceManager.GetString("NotFoundLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&lt;a target=&apos;_blank&apos; href=&quot;@PageURL &quot;&gt;@PageName&lt;/a&gt; &lt;/span&gt;.
        /// </summary>
        internal static string PageLink {
            get {
                return ResourceManager.GetString("PageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PageName.
        /// </summary>
        internal static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PageURL.
        /// </summary>
        internal static string PageURL {
            get {
                return ResourceManager.GetString("PageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       تم القيام بعملية  تغيير كلمة المرور .
        /// </summary>
        internal static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الدخول إلى صفحة   .
        /// </summary>
        internal static string ViewText {
            get {
                return ResourceManager.GetString("ViewText", resourceCulture);
            }
        }
    }
}
