//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.DataModel.QvDataAnnotation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApplication.DataModel.QvDataAnnotation.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب البنكى موجود من قبل.
        /// </summary>
        public static string BankAccountExists {
            get {
                return ResourceManager.GetString("BankAccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب البنك غير صحيح .رقم الحساب مكون من 22 رقم مسبوق بحرفين.
        /// </summary>
        public static string BankAcountNum {
            get {
                return ResourceManager.GetString("BankAcountNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب محظور لمدة 15 دقيقة.
        /// </summary>
        public static string BlockMessage {
            get {
                return ResourceManager.GetString("BlockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 200حرف و مسموح بكتابه حروف فقط ..
        /// </summary>
        public static string CharactersOnly200 {
            get {
                return ResourceManager.GetString("CharactersOnly200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الكود موجود بالفعل.
        /// </summary>
        public static string CodeExists {
            get {
                return ResourceManager.GetString("CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مطابق.
        /// </summary>
        public static string CompareValidator {
            get {
                return ResourceManager.GetString("CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال كود بلد صحيح .
        /// </summary>
        public static string countrycodevalid {
            get {
                return ResourceManager.GetString("countrycodevalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تغيير الحالة مرة أخري في نفس التاريخ.
        /// </summary>
        public static string DateExists {
            get {
                return ResourceManager.GetString("DateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بإستخدام رموز خاصة.
        /// </summary>
        public static string DenaySpecialChar {
            get {
                return ResourceManager.GetString("DenaySpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه البيانات تم إدخالها مسبقا.
        /// </summary>
        public static string DublicatedItem {
            get {
                return ResourceManager.GetString("DublicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد زيارة في نفس التاريخ.
        /// </summary>
        public static string DuplicatedVisitDate {
            get {
                return ResourceManager.GetString("DuplicatedVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الزيارة موجود بالفعل.
        /// </summary>
        public static string DuplicatedVisitNo {
            get {
                return ResourceManager.GetString("DuplicatedVisitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد زيارة في نفس التاريخ.
        /// </summary>
        public static string DuplicatedVisitType {
            get {
                return ResourceManager.GetString("DuplicatedVisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاء إدخال بريد إلكتروني صحيح.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاء إدخال بريد إلكتروني صحيح بحد اقصى 50 حرف .
        /// </summary>
        public static string EmailChar50 {
            get {
                return ResourceManager.GetString("EmailChar50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكترونى موجود بالفعل.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحروف تجاوز العدد المسموح.
        /// </summary>
        public static string EmailLength {
            get {
                return ResourceManager.GetString("EmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string er {
            get {
                return ResourceManager.GetString("er", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الفحص موجود من قبل.
        /// </summary>
        public static string ExamExists {
            get {
                return ResourceManager.GetString("ExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب فيس بوك غير صحيح.
        /// </summary>
        public static string FaceBook {
            get {
                return ResourceManager.GetString("FaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب جوجل غير صحيح.
        /// </summary>
        public static string GooglePlus {
            get {
                return ResourceManager.GetString("GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد الصوره غير مطابقة.
        /// </summary>
        public static string InValidImageSize {
            get {
                return ResourceManager.GetString("InValidImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود بالفعل.
        /// </summary>
        public static string KnowingClinicExists {
            get {
                return ResourceManager.GetString("KnowingClinicExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يقل عدد الأرقام عن 10 أرقام.
        /// </summary>
        public static string Length10 {
            get {
                return ResourceManager.GetString("Length10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الأرقام عن 15 رقم.
        /// </summary>
        public static string Length15 {
            get {
                return ResourceManager.GetString("Length15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 150 حرف.
        /// </summary>
        public static string Length150 {
            get {
                return ResourceManager.GetString("Length150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن  لايقل عدد الحروف عن 5 احرف.
        /// </summary>
        public static string Length5 {
            get {
                return ResourceManager.GetString("Length5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 50حرف.
        /// </summary>
        public static string Length50 {
            get {
                return ResourceManager.GetString("Length50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد عدد الحروف عن 200حرف و مسموح بكتابة حروف و  أرقام فقط ..
        /// </summary>
        public static string lettersandnumbersonly {
            get {
                return ResourceManager.GetString("lettersandnumbersonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب  أن لا يزيد عدد الحروف عن 350حرف و غير مسموح بكتابه رموز خاصة ماعدا(: , - _).
        /// </summary>
        public static string lettersnumbersspecialchar {
            get {
                return ResourceManager.GetString("lettersnumbersspecialchar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول موجود من قبل.
        /// </summary>
        public static string LoginNameExists {
            get {
                return ResourceManager.GetString("LoginNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صندوق البريد 5 أرقام فقط.
        /// </summary>
        public static string MailBoxNo {
            get {
                return ResourceManager.GetString("MailBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إختيار ملف أكبر من 500 ميجا.
        /// </summary>
        public static string MediaSize {
            get {
                return ResourceManager.GetString("MediaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الملف غير صحيح.
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال أرقام بحد أقصى 15 رقم و حد أدنى 10 أرقام.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم مسجل بالفعل بالبرنامج نأمل التأكد من الرقم الصحيح.
        /// </summary>
        public static string MobileExists {
            get {
                return ResourceManager.GetString("MobileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاسم موجود من قبل.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقبل 10 ارقام فقط.
        /// </summary>
        public static string NationalIdNo {
            get {
                return ResourceManager.GetString("NationalIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسموح بإدخال بحد أقصى 20 حروف و ارقام فقط  .
        /// </summary>
        public static string NationalIdNo2 {
            get {
                return ResourceManager.GetString("NationalIdNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد بيانات حاليا.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ارقام فقط ماعدا الصفر و رقم سالب.
        /// </summary>
        public static string NumberOnlyExpectMinus {
            get {
                return ResourceManager.GetString("NumberOnlyExpectMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ارقام فقط ماعدا رقم سالب.
        /// </summary>
        public static string NumberOnlyExpectMinuss {
            get {
                return ResourceManager.GetString("NumberOnlyExpectMinuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 10 رقم.
        /// </summary>
        public static string NumbersOnly10 {
            get {
                return ResourceManager.GetString("NumbersOnly10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 15 رقم.
        /// </summary>
        public static string NumbersOnly15 {
            get {
                return ResourceManager.GetString("NumbersOnly15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و أن لا تزيد عن رقمين.
        /// </summary>
        public static string NumbersOnly2 {
            get {
                return ResourceManager.GetString("NumbersOnly2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و أن لا تزيد عن 4  أرقام.
        /// </summary>
        public static string NumbersOnly4 {
            get {
                return ResourceManager.GetString("NumbersOnly4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 5 أرقام.
        /// </summary>
        public static string NumbersOnly5 {
            get {
                return ResourceManager.GetString("NumbersOnly5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 50 رقم.
        /// </summary>
        public static string NumbersOnly50 {
            get {
                return ResourceManager.GetString("NumbersOnly50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف غير صحيح.
        /// </summary>
        public static string NumbersOnly7Digit {
            get {
                return ResourceManager.GetString("NumbersOnly7Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 9 رقم.
        /// </summary>
        public static string NumbersOnly9 {
            get {
                return ResourceManager.GetString("NumbersOnly9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال أرقام فقط ولا يزيد عن رقمين.
        /// </summary>
        public static string NumbersOnlyTwoDigit {
            get {
                return ResourceManager.GetString("NumbersOnlyTwoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و يجب ان لا يزيد عدد الأرقام عن 30 رقم.
        /// </summary>
        public static string NumbersUpto30 {
            get {
                return ResourceManager.GetString("NumbersUpto30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الترتيب موجود من قبل.
        /// </summary>
        public static string OrderExists {
            get {
                return ResourceManager.GetString("OrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم موجود بالفعل علي مستوي الفرع ،رجاء التأكد من الرقم الصحيح .
        /// </summary>
        public static string PaperFileNoExists {
            get {
                return ResourceManager.GetString("PaperFileNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال أرقام بحد أقصى 15 رقم و حد أدنى7 أرقام.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال أرقام بحد أقصى 15 رقم و حد أدنى9 أرقام.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال ارقام فقط ... وتكون 9 ارقام فقط.
        /// </summary>
        public static string Phone9 {
            get {
                return ResourceManager.GetString("Phone9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن يتراوح رقم البورت مابين 0 و 65535.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي يجب أن يكون رقم مكون من 5 أرقام.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاء المرور من اختبار التحقق من الهوية بشكل صحيح.
        /// </summary>
        public static string RecaptchaValidation {
            get {
                return ResourceManager.GetString("RecaptchaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التصريح موجود من قبل.
        /// </summary>
        public static string RegisterationNumberExists {
            get {
                return ResourceManager.GetString("RegisterationNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الأرقام عن 11 رقم.
        /// </summary>
        public static string registrationNum {
            get {
                return ResourceManager.GetString("registrationNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن ترك هذه الخانة فارغة.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك ترك هذه الخانة فارغة.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار ملف السيرة الذاتية.
        /// </summary>
        public static string RequiredFile {
            get {
                return ResourceManager.GetString("RequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 100 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString100 {
            get {
                return ResourceManager.GetString("SafeString100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString1000 {
            get {
                return ResourceManager.GetString("SafeString1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 15 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString15 {
            get {
                return ResourceManager.GetString("SafeString15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString150 {
            get {
                return ResourceManager.GetString("SafeString150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 20 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString20 {
            get {
                return ResourceManager.GetString("SafeString20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 200 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString200 {
            get {
                return ResourceManager.GetString("SafeString200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 250 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString250 {
            get {
                return ResourceManager.GetString("SafeString250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 300 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString300 {
            get {
                return ResourceManager.GetString("SafeString300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 350 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString350 {
            get {
                return ResourceManager.GetString("SafeString350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 400 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString400 {
            get {
                return ResourceManager.GetString("SafeString400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 450 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString450 {
            get {
                return ResourceManager.GetString("SafeString450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString50 {
            get {
                return ResourceManager.GetString("SafeString50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 500 حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString500 {
            get {
                return ResourceManager.GetString("SafeString500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 6حرف و غير مسموح بكتابة رموز غير آمنة.
        /// </summary>
        public static string SafeString6 {
            get {
                return ResourceManager.GetString("SafeString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 100 حرف و غير مسموح بكتابة رموز غير آمنة أو أرقام.
        /// </summary>
        public static string SafeStringNoNum100 {
            get {
                return ResourceManager.GetString("SafeStringNoNum100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150 حرف و غير مسموح بكتابة رموز غير آمنة أو أرقام.
        /// </summary>
        public static string SafeStringNoNum150 {
            get {
                return ResourceManager.GetString("SafeStringNoNum150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السبب موجود بالفعل.
        /// </summary>
        public static string SmokingReasonExists {
            get {
                return ResourceManager.GetString("SmokingReasonExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون فترة التدخين من أقل من الي.
        /// </summary>
        public static string SmokingTimeFromTo {
            get {
                return ResourceManager.GetString("SmokingTimeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النوع موجودبالفعل .
        /// </summary>
        public static string SmokingTypeExists {
            get {
                return ResourceManager.GetString("SmokingTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه الوحدة موجودة بالفعل.
        /// </summary>
        public static string SmokingUnitExists {
            get {
                return ResourceManager.GetString("SmokingUnitExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailChar50.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العرض مسجل بالفعل.
        /// </summary>
        public static string SyndromeExists {
            get {
                return ResourceManager.GetString("SyndromeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا لابد من الموافقة على الشروط والاحكام لاتمام الحفظ.
        /// </summary>
        public static string TermsAndConditionsRequired {
            get {
                return ResourceManager.GetString("TermsAndConditionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تويتر غير صحيح.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا لا يمكن التعديل لهذا التاريخ الوحدات مشغولة.
        /// </summary>
        public static string UpdateDateError {
            get {
                return ResourceManager.GetString("UpdateDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عن 13 رقم و لا يقل عن 10 أرقام.
        /// </summary>
        public static string ValidateMobile {
            get {
                return ResourceManager.GetString("ValidateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  التعليق فارغ . .
        /// </summary>
        public static string ValidCommentRequired {
            get {
                return ResourceManager.GetString("ValidCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار منطقة المسجد ..
        /// </summary>
        public static string ValidComparerAreaddl {
            get {
                return ResourceManager.GetString("ValidComparerAreaddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار قسم للمقاله ..
        /// </summary>
        public static string ValidComparerCategoryddl {
            get {
                return ResourceManager.GetString("ValidComparerCategoryddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه السر غير متطابقه ..
        /// </summary>
        public static string ValidComparerPassword {
            get {
                return ResourceManager.GetString("ValidComparerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار قمر للقناه ..
        /// </summary>
        public static string ValidComparerSatddl {
            get {
                return ResourceManager.GetString("ValidComparerSatddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام بحد أقصى 15 ارقام (13 أرقام صحيحة - 2 رقمين عشريين و العلامة العشرية ).
        /// </summary>
        public static string ValidDecimal15Num {
            get {
                return ResourceManager.GetString("ValidDecimal15Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام بحد أقصى 10 ارقام (7 أرقام صحيحة - 2 رقمين عشريين و العلامة العشرية ) .
        /// </summary>
        public static string ValidDecimalNum {
            get {
                return ResourceManager.GetString("ValidDecimalNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام بحد أقصى 10 ارقام (7 أرقام صحيحة - 3 رقمين عشريين و العلامة العشرية ).
        /// </summary>
        public static string ValidDecimalNum3 {
            get {
                return ResourceManager.GetString("ValidDecimalNum3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام بحد أقصى 10 ارقام ولا يسمح بأصفار فقط (7 أرقام صحيحة - 2 رقمين عشريين و العلامة العشرية ) .
        /// </summary>
        public static string ValidDecimalNumWithoutZero {
            get {
                return ResourceManager.GetString("ValidDecimalNumWithoutZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد الحذف ؟ ..
        /// </summary>
        public static string ValidDelete {
            get {
                return ResourceManager.GetString("ValidDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  البريد الإلكتروني فارغ ..
        /// </summary>
        public static string ValidEmailRequired {
            get {
                return ResourceManager.GetString("ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم العمليه بنجاح ..
        /// </summary>
        public static string ValidFailure {
            get {
                return ResourceManager.GetString("ValidFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء  إدخال رقم جوال صحيح.
        /// </summary>
        public static string ValidJawal {
            get {
                return ResourceManager.GetString("ValidJawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال أرقام فقط .. بشكل صحيح مثال 31.205753.
        /// </summary>
        public static string validLatitudeLongitiude {
            get {
                return ResourceManager.GetString("validLatitudeLongitiude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اسم دخول غير مسموح يجب ألا يحتوى على رموز خاصة أو فراغات.
        /// </summary>
        public static string ValidLoginName {
            get {
                return ResourceManager.GetString("ValidLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال https://www.google.com.eg/maps/@31.2527269,29.9749954,16z.
        /// </summary>
        public static string ValidMapURL {
            get {
                return ResourceManager.GetString("ValidMapURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون عدد الحروف من 6 الى 150 حرف ولا يجب ادخال رموز خاصة .
        /// </summary>
        public static string ValidNameRange {
            get {
                return ResourceManager.GetString("ValidNameRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  كلمة السر يجب ان تكون بين 4 و 8 حروف أو أرقام و تشمل ما لا يقل عن رقم واحد.
        /// </summary>
        public static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال رقم هاتف صحيح.
        /// </summary>
        public static string ValidPhoneNo {
            get {
                return ResourceManager.GetString("ValidPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب ادخال ارقام فقط و بشكل صحيح  00966xxxxxxxxxx.
        /// </summary>
        public static string validPhoneSaudiArabia {
            get {
                return ResourceManager.GetString("validPhoneSaudiArabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم صحيح موجب.
        /// </summary>
        public static string ValidPositiveIntegerNumber {
            get {
                return ResourceManager.GetString("ValidPositiveIntegerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم موجب.
        /// </summary>
        public static string ValidPositiveNumber {
            get {
                return ResourceManager.GetString("ValidPositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال أرقام فقط و أن لا تزيد عن 10 أرقام.
        /// </summary>
        public static string ValidPrice {
            get {
                return ResourceManager.GetString("ValidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaDetail {
            get {
                return ResourceManager.GetString("ValidRegulaDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularDescriptionChannel {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularDescriptionInterviewer {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionInterviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularDescriptionProgram {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكترونى غير صحيح ..
        /// </summary>
        public static string ValidRegularEmail {
            get {
                return ResourceManager.GetString("ValidRegularEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 100 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName100 {
            get {
                return ResourceManager.GetString("ValidRegularFullName100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد عدد الحروف عن 150 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName150 {
            get {
                return ResourceManager.GetString("ValidRegularFullName150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقبل حروف فقط ويجب ان لا يزيد عدد الحروف عن 150حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName150StringOnly {
            get {
                return ResourceManager.GetString("ValidRegularFullName150StringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 20 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName20 {
            get {
                return ResourceManager.GetString("ValidRegularFullName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد عدد الحروف عن 200 حرف و غير مسموح بكتابة رموز خاصة..
        /// </summary>
        public static string ValidRegularFullName200 {
            get {
                return ResourceManager.GetString("ValidRegularFullName200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 22حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularFullName22 {
            get {
                return ResourceManager.GetString("ValidRegularFullName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 250 حرف و غير مسموح بكتابه رموز خاصه..
        /// </summary>
        public static string ValidRegularFullName250 {
            get {
                return ResourceManager.GetString("ValidRegularFullName250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 400 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName400 {
            get {
                return ResourceManager.GetString("ValidRegularFullName400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 450 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName450 {
            get {
                return ResourceManager.GetString("ValidRegularFullName450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName50 {
            get {
                return ResourceManager.GetString("ValidRegularFullName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يقبل حروف فقط ويجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName50StringOnly {
            get {
                return ResourceManager.GetString("ValidRegularFullName50StringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 6 احرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName6 {
            get {
                return ResourceManager.GetString("ValidRegularFullName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 750 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularFullName750 {
            get {
                return ResourceManager.GetString("ValidRegularFullName750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 10 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularName10 {
            get {
                return ResourceManager.GetString("ValidRegularName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 15 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularName15 {
            get {
                return ResourceManager.GetString("ValidRegularName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال حروف فقط و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularNameMax {
            get {
                return ResourceManager.GetString("ValidRegularNameMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عن 15 رقم و لا يقل عن 11 رقم ..
        /// </summary>
        public static string ValidRegularPhone {
            get {
                return ResourceManager.GetString("ValidRegularPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بكتابه رموز خاصه .
        /// </summary>
        public static string ValidRegularSummary {
            get {
                return ResourceManager.GetString("ValidRegularSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 180 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary180 {
            get {
                return ResourceManager.GetString("ValidRegularSummary180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 200 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary200 {
            get {
                return ResourceManager.GetString("ValidRegularSummary200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 2000 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary2000 {
            get {
                return ResourceManager.GetString("ValidRegularSummary2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 300 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary300 {
            get {
                return ResourceManager.GetString("ValidRegularSummary300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 350 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary350 {
            get {
                return ResourceManager.GetString("ValidRegularSummary350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 500 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary500 {
            get {
                return ResourceManager.GetString("ValidRegularSummary500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 600 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummary600 {
            get {
                return ResourceManager.GetString("ValidRegularSummary600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد عدد الحروف عن  750حرف و غير مسموح بكتابة رموز خاصة.
        /// </summary>
        public static string ValidRegularSummary750 {
            get {
                return ResourceManager.GetString("ValidRegularSummary750", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 120حرف أو يقل عن 80 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegularSummaryProgram {
            get {
                return ResourceManager.GetString("ValidRegularSummaryProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 100حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegulaTitler100 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegulaTitler150 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 20 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaTitler20 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد عدد الحروف عن 200حرف و غير مسموح بكتابة رموز خاصة..
        /// </summary>
        public static string ValidRegulaTitler200 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 250 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaTitler250 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 40 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegulaTitler40 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegulaTitler50 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 500حرف و غير مسموح بكتابة رموز خاصة ..
        /// </summary>
        public static string ValidRegulaTitler500 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string ValidRepeatPassword {
            get {
                return ResourceManager.GetString("ValidRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب أن لا تترك الخانات فارغة.
        /// </summary>
        public static string ValidRequired {
            get {
                return ResourceManager.GetString("ValidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ValidRequiredwithBR {
            get {
                return ResourceManager.GetString("ValidRequiredwithBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بكتابه رموز غير آمنة  .
        /// </summary>
        public static string ValidSafeString {
            get {
                return ResourceManager.GetString("ValidSafeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تمت العمليه بنجاح ..
        /// </summary>
        public static string ValidSuccess {
            get {
                return ResourceManager.GetString("ValidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال ملف فلاش.
        /// </summary>
        public static string ValidSWFFile {
            get {
                return ResourceManager.GetString("ValidSWFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  العنوان فارغ ..
        /// </summary>
        public static string ValidTitleRequired {
            get {
                return ResourceManager.GetString("ValidTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  إدخال  أرقام فقط و أن لا تزيد عن 6 أرقام.
        /// </summary>
        public static string ValidUnitPrice {
            get {
                return ResourceManager.GetString("ValidUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال http://www.mysite.com ..
        /// </summary>
        public static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال http://www.facebook.com/pagename.
        /// </summary>
        public static string ValidUrlFaceBook {
            get {
                return ResourceManager.GetString("ValidUrlFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الرابط بشكل صحيح مثال http://plus.google.com/pagename.
        /// </summary>
        public static string ValidUrlGooglePlus {
            get {
                return ResourceManager.GetString("ValidUrlGooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال https://www.instagram.com/pagename.
        /// </summary>
        public static string ValidUrlInstagram {
            get {
                return ResourceManager.GetString("ValidUrlInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال http://www.twitter.com/pagename.
        /// </summary>
        public static string ValidUrlTwitter {
            get {
                return ResourceManager.GetString("ValidUrlTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال http://www.youtube.com/pagename.
        /// </summary>
        public static string ValidUrlYoutube {
            get {
                return ResourceManager.GetString("ValidUrlYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخال الرابط بشكل صحيح مثال http://www.youtube.com/watch?v=videocode.
        /// </summary>
        public static string ValidUrlYoutubeVideo {
            get {
                return ResourceManager.GetString("ValidUrlYoutubeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء  إدخال 10 أرقام فقط.
        /// </summary>
        public static string ValiedCivilNum {
            get {
                return ResourceManager.GetString("ValiedCivilNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء  إدخال سعر مناسب.
        /// </summary>
        public static string ValiedCurrency {
            get {
                return ResourceManager.GetString("ValiedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يقل الرقم عن 1.
        /// </summary>
        public static string ValiedFAQOrder {
            get {
                return ResourceManager.GetString("ValiedFAQOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم غير صحيح .
        /// </summary>
        public static string ValiedInt {
            get {
                return ResourceManager.GetString("ValiedInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 150 حرف ..
        /// </summary>
        public static string Valiedmax150 {
            get {
                return ResourceManager.GetString("Valiedmax150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الخانات عن 20.
        /// </summary>
        public static string Valiedmax20 {
            get {
                return ResourceManager.GetString("Valiedmax20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 250 حرف ..
        /// </summary>
        public static string Valiedmax250 {
            get {
                return ResourceManager.GetString("Valiedmax250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن لا يزيد عدد الحروف عن 50 حرف ..
        /// </summary>
        public static string Valiedmax50 {
            get {
                return ResourceManager.GetString("Valiedmax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء  إدخال رقم موجب.
        /// </summary>
        public static string ValiedNumber {
            get {
                return ResourceManager.GetString("ValiedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار نوع الهاتف..
        /// </summary>
        public static string ValiedPhoneType {
            get {
                return ResourceManager.GetString("ValiedPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء أن لا يقل عدد الأرقام عن 1  و أن لا يزيد عن 6 .
        /// </summary>
        public static string ValiedPortNo {
            get {
                return ResourceManager.GetString("ValiedPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب  أن تكتب راقم لا يزيد عن 1024 ولا يقل عن 0.
        /// </summary>
        public static string ValiedRange {
            get {
                return ResourceManager.GetString("ValiedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء  إدخال رقم بين 0 إلى 10.
        /// </summary>
        public static string ValiedRange10 {
            get {
                return ResourceManager.GetString("ValiedRange10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * يجب أن لا تترك هذه الخانة فارغة.
        /// </summary>
        public static string ValiedReq {
            get {
                return ResourceManager.GetString("ValiedReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال  أرقام بحد أقصى 15رقم و حد أدنى 7رقم.
        /// </summary>
        public static string vrPhone {
            get {
                return ResourceManager.GetString("vrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور القديمة غير صحيحة.
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب يوتيوب غير صحيح.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
    }
}
