//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.DataService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataServiceArabicResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataServiceArabicResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApplication.DataService.DataServiceArabicResource", typeof(DataServiceArabicResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء الرحلة.
        /// </summary>
        internal static string CancelShipment {
            get {
                return ResourceManager.GetString("CancelShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  السيارة .
        /// </summary>
        internal static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  التاجر.
        /// </summary>
        internal static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  متجر التاجر .
        /// </summary>
        internal static string DealerStore {
            get {
                return ResourceManager.GetString("DealerStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  السائق .
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء الرحلة عن طريق السائق.
        /// </summary>
        internal static string DriverCancel {
            get {
                return ResourceManager.GetString("DriverCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم توصيل شحنتك.
        /// </summary>
        internal static string DriverDeliverdTheShipment {
            get {
                return ResourceManager.GetString("DriverDeliverdTheShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد أتم السائق توصيل شحنتك إلي مكان التسليم المحدد.
        /// </summary>
        internal static string DriverDeliverdTheShipmentToThePoint {
            get {
                return ResourceManager.GetString("DriverDeliverdTheShipmentToThePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم تعيين السائق.
        /// </summary>
        internal static string DriverHasBeenAssigned {
            get {
                return ResourceManager.GetString("DriverHasBeenAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعيين سائق لتوصيل شحنتك.
        /// </summary>
        internal static string DriverHasBeenAssignedForYourShipment {
            get {
                return ResourceManager.GetString("DriverHasBeenAssignedForYourShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام السائق لشحنتك.
        /// </summary>
        internal static string DriverHasRecivedShipment {
            get {
                return ResourceManager.GetString("DriverHasRecivedShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد قام السائق باستلام شحنتك وفي طريقه للتوصيل لمكان التسليم المحدد.
        /// </summary>
        internal static string DriverHasRecivedShipmentAndInWayNow {
            get {
                return ResourceManager.GetString("DriverHasRecivedShipmentAndInWayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقترب السائق من الوصول الي النقطه المحدده .
        /// </summary>
        internal static string DriverPreArrivalMassage {
            get {
                return ResourceManager.GetString("DriverPreArrivalMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقترب السائق من الوصول .
        /// </summary>
        internal static string DriverPreArrivalTitle {
            get {
                return ResourceManager.GetString("DriverPreArrivalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  م .
        /// </summary>
        internal static string Evining {
            get {
                return ResourceManager.GetString("Evining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تحميل الملف .
        /// </summary>
        internal static string FileLoad {
            get {
                return ResourceManager.GetString("FileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاستلام شحنتك رقم سيارته.
        /// </summary>
        internal static string ForDeliverYourShipment {
            get {
                return ResourceManager.GetString("ForDeliverYourShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  من .
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  من مجموعة .
        /// </summary>
        internal static string FromGroup {
            get {
                return ResourceManager.GetString("FromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  من المجموعات .
        /// </summary>
        internal static string FromGroups {
            get {
                return ResourceManager.GetString("FromGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  البضائع .
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تم إضافة .
        /// </summary>
        internal static string HasAdded {
            get {
                return ResourceManager.GetString("HasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تم حذف .
        /// </summary>
        internal static string HasDeleted {
            get {
                return ResourceManager.GetString("HasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تم تعيين .
        /// </summary>
        internal static string HasDesignation {
            get {
                return ResourceManager.GetString("HasDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عرض الصورة .
        /// </summary>
        internal static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  فى .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الاعدادات.
        /// </summary>
        internal static string ManageSettings {
            get {
                return ResourceManager.GetString("ManageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء الرحلة عن طريق التاجر.
        /// </summary>
        internal static string MerchantCancel {
            get {
                return ResourceManager.GetString("MerchantCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ص .
        /// </summary>
        internal static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  طلب توصيل جديد .
        /// </summary>
        internal static string NewDeliveryRequest {
            get {
                return ResourceManager.GetString("NewDeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يوجد طلب توصيل شحنة .
        /// </summary>
        internal static string NewShipmentDeliveryRequest {
            get {
                return ResourceManager.GetString("NewShipmentDeliveryRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا .
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على سائقين للشحنة الخاصة بك.
        /// </summary>
        internal static string NoDriverFound {
            get {
                return ResourceManager.GetString("NoDriverFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا يوجد ملف .
        /// </summary>
        internal static string NoFileExist {
            get {
                return ResourceManager.GetString("NoFileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لم يتم الدخول من قبل .
        /// </summary>
        internal static string NoSignInBefore {
            get {
                return ResourceManager.GetString("NoSignInBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  بسبب .
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  إلى .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   المستخدم  .
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   تم اضافه المستخدم  .
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نعم .
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
