//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleItemExplanation = new HashSet<ArticleItemExplanation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ArticleContent { get; set; }
    
        public virtual ICollection<ArticleItemExplanation> ArticleItemExplanation { get; set; }
    }
}
