//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayah
    {
        public Ayah()
        {
            this.UserAyat = new HashSet<UserAyat>();
        }
    
        public int id { get; set; }
        public int surah { get; set; }
        public int ayah_num { get; set; }
        public string verse { get; set; }
        public Nullable<int> Juz { get; set; }
        public int DbIndex { get; set; }
        public Nullable<int> PageNum { get; set; }
    
        public virtual Juz Juz1 { get; set; }
        public virtual Surah Surah1 { get; set; }
        public virtual ICollection<UserAyat> UserAyat { get; set; }
    }
}
