//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Imagepath { get; set; }
        public string ImageDescription { get; set; }
        public Nullable<int> ContentCategoryID { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public string PermenantKey { get; set; }
        public string SeoData { get; set; }
        public string SeoTargetKey { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoMetaKey { get; set; }
        public string SeoUrl { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Videopath { get; set; }
    
        public virtual ContentCategory ContentCategory { get; set; }
    }
}
