//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentCategory
    {
        public ContentCategory()
        {
            this.Content = new HashSet<Content>();
            this.ContentCategory1 = new HashSet<ContentCategory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> AllowComments { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsPermanent { get; set; }
        public bool HasSummary { get; set; }
        public bool HasDetails { get; set; }
        public bool HasPublishDate { get; set; }
        public bool HasImage { get; set; }
        public int TitleMaxLength { get; set; }
        public int SummaryMaxLength { get; set; }
        public int ImageWidth { get; set; }
        public int ImageHeight { get; set; }
        public Nullable<bool> HasVideo { get; set; }
        public Nullable<int> MaxActiveContent { get; set; }
    
        public virtual ICollection<Content> Content { get; set; }
        public virtual ICollection<ContentCategory> ContentCategory1 { get; set; }
        public virtual ContentCategory ContentCategory2 { get; set; }
    }
}
