//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Action
    {
        public CU_Action()
        {
            this.CU_Log = new HashSet<CU_Log>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdProgram { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public bool IsSecurity { get; set; }
        public int Order { get; set; }
    
        public virtual CU_Program CU_Program { get; set; }
        public virtual ICollection<CU_Log> CU_Log { get; set; }
    }
}
