//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Employee
    {
        public CU_Employee()
        {
            this.CU_Employee_Role = new HashSet<CU_Employee_Role>();
            this.CU_Employee_RoleProgram = new HashSet<CU_Employee_RoleProgram>();
            this.CU_Log = new HashSet<CU_Log>();
            this.Notification = new HashSet<Notification>();
            this.NotificationUser = new HashSet<NotificationUser>();
            this.ResetPasswordRequest = new HashSet<ResetPasswordRequest>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdJob { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IdDepartment { get; set; }
        public Nullable<int> IdHeadDepartment { get; set; }
        public Nullable<bool> IsTrainee { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> LastVisitTime { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> IdEmployeeCategory { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual CU_Branch CU_Branch { get; set; }
        public virtual CU_Department CU_Department { get; set; }
        public virtual CU_Department CU_Department1 { get; set; }
        public virtual CU_EmployeeCategory CU_EmployeeCategory { get; set; }
        public virtual CU_Job CU_Job { get; set; }
        public virtual ICollection<CU_Employee_Role> CU_Employee_Role { get; set; }
        public virtual ICollection<CU_Employee_RoleProgram> CU_Employee_RoleProgram { get; set; }
        public virtual ICollection<CU_Log> CU_Log { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual ICollection<NotificationUser> NotificationUser { get; set; }
        public virtual ICollection<ResetPasswordRequest> ResetPasswordRequest { get; set; }
    }
}
