//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_HeadDepartment
    {
        public CU_HeadDepartment()
        {
            this.CU_Department = new HashSet<CU_Department>();
            this.CU_HeadDepartment1 = new HashSet<CU_HeadDepartment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string MainTask { get; set; }
        public Nullable<int> IdParent { get; set; }
    
        public virtual ICollection<CU_Department> CU_Department { get; set; }
        public virtual ICollection<CU_HeadDepartment> CU_HeadDepartment1 { get; set; }
        public virtual CU_HeadDepartment CU_HeadDepartment2 { get; set; }
    }
}
