//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Log
    {
        public int LogID { get; set; }
        public int IdAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int IdEmployee { get; set; }
        public Nullable<int> IdPage { get; set; }
        public string Value { get; set; }
        public string IpAddress { get; set; }
        public string ActionName { get; set; }
    
        public virtual CU_Action CU_Action { get; set; }
        public virtual CU_Employee CU_Employee { get; set; }
        public virtual CU_Page CU_Page { get; set; }
    }
}
