//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CU_Page
    {
        public CU_Page()
        {
            this.CU_Log = new HashSet<CU_Log>();
            this.CU_Page1 = new HashSet<CU_Page>();
            this.CU_Role_Page = new HashSet<CU_Role_Page>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public int IdProgram { get; set; }
        public bool IsDeleted { get; set; }
        public string Actions { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> PageOrder { get; set; }
        public bool IsVisible { get; set; }
    
        public virtual ICollection<CU_Log> CU_Log { get; set; }
        public virtual ICollection<CU_Page> CU_Page1 { get; set; }
        public virtual CU_Page CU_Page2 { get; set; }
        public virtual CU_Program CU_Program { get; set; }
        public virtual ICollection<CU_Role_Page> CU_Role_Page { get; set; }
    }
}
