//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doaa
    {
        public Doaa()
        {
            this.DoaaItemSource = new HashSet<DoaaItemSource>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DoaaMainCategoryID { get; set; }
        public string Name { get; set; }
        public string DoaaContent { get; set; }
        public string DoaaMeanings { get; set; }
    
        public virtual DoaaMainCategory DoaaMainCategory { get; set; }
        public virtual ICollection<DoaaItemSource> DoaaItemSource { get; set; }
    }
}
