//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupTarget = new HashSet<GroupTarget>();
            this.GroupUser = new HashSet<GroupUser>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> MoshafID { get; set; }
    
        public virtual Moshaf Moshaf { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<GroupTarget> GroupTarget { get; set; }
        public virtual ICollection<GroupUser> GroupUser { get; set; }
    }
}
