//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juz
    {
        public Juz()
        {
            this.Ayah = new HashSet<Ayah>();
            this.Surah = new HashSet<Surah>();
        }
    
        public int Id { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }
        public string Name { get; set; }
        public Nullable<int> StartAyah { get; set; }
        public Nullable<int> EndAyah { get; set; }
    
        public virtual ICollection<Ayah> Ayah { get; set; }
        public virtual ICollection<Surah> Surah { get; set; }
    }
}
