//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamesOfAllah
    {
        public int ID { get; set; }
        public string NameOfAllahImage { get; set; }
        public string NameOfAllah { get; set; }
        public string NameOfAllahMeaning { get; set; }
        public int Number { get; set; }
    }
}
