//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationUser = new HashSet<NotificationUser>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public Nullable<int> FromAppUserID { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual CU_Employee CU_Employee { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<NotificationUser> NotificationUser { get; set; }
    }
}
