//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationLog
    {
        public int ID { get; set; }
        public string NotificationPayload { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
