//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPasswordRequest
    {
        public int ResetPasswordID { get; set; }
        public int EmployeeID { get; set; }
        public string GUID { get; set; }
        public System.DateTime ResetRequestDateTime { get; set; }
        public bool IsExpired { get; set; }
    
        public virtual CU_Employee CU_Employee { get; set; }
    }
}
