//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingID { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PortNo { get; set; }
        public string FromEmail { get; set; }
        public bool NameIsVisible { get; set; }
        public bool NameIsRequired { get; set; }
        public bool SSL { get; set; }
        public string SmsServer { get; set; }
        public string SmsUserName { get; set; }
        public string SmsPassWord { get; set; }
        public Nullable<int> SmsPort { get; set; }
        public string SmsFrom { get; set; }
        public string SmsUrlString { get; set; }
        public string WahtsAppNo { get; set; }
        public string WhatsAppPassword { get; set; }
        public string WhatsAppCode { get; set; }
        public string HrEmail { get; set; }
        public string ContactInfo { get; set; }
        public string CompetitionURL { get; set; }
        public string SurveyUrl { get; set; }
        public string YoutubeUrl { get; set; }
        public string FaceBookUrl { get; set; }
        public string twitterUrl { get; set; }
    }
}
