//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Message
    {
        public int ID { get; set; }
        public string TextMessage { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<int> ResponseNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
