//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetType
    {
        public TargetType()
        {
            this.GroupTarget = new HashSet<GroupTarget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<GroupTarget> GroupTarget { get; set; }
    }
}
