//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApplication.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Group = new HashSet<Group>();
            this.GroupUser = new HashSet<GroupUser>();
            this.UserAyat = new HashSet<UserAyat>();
            this.UserCode = new HashSet<UserCode>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsMale { get; set; }
        public bool IsActive { get; set; }
        public string GCMID { get; set; }
        public string APNID { get; set; }
    
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<GroupUser> GroupUser { get; set; }
        public virtual ICollection<UserAyat> UserAyat { get; set; }
        public virtual ICollection<UserCode> UserCode { get; set; }
    }
}
